### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by adrianojn** [adrianojn/ygopro#1]
- [ ] clone ygopro-fh discarding its git histoy
- [ ] add ygoprox libs (with the linux fixes)
- [ ] add configurations for:
  - [ ] R key
  - [ ]  DB file
  - [ ] pics folder
  - [ ] scripts folder
  - [ ] strings.conf
  - [ ] sounds folder
- [ ] add forced join mode
- [ ] add sounds
- [ ] add skins
- [ ] add "provider server" (a url)
- [ ] add cover image per the "provider server"
- [ ] add avatar per the "provider server"
- [ ] Configurable display of Elo/Rank before game start
- [ ] elo/rank provided by "provider server"
